phrases:
   - example_phrase%b%&3This is an example phrase!
   - Unknown_Command%b%&4Unknown Command! &fType 'help' for help.
   - No_Permission%b%&4You do not have permission to do this.
settings:
   phrase-fallback: true
   error-message: The requested phrase could not be found!